-- 역할테이블, 유저테이블
-- (공지사항, qna, 신고하기... / QNA도 댓글로 관리자가 달아주기)일반게시글테이블, 일반게시글사진테이블, 일반게시글댓글테이블
-- (**추천) 장소게시글테이블, 장소게시글사진테이블, 장소게시글댓글테이블, 장소게시글저장테이블
-- (구글API?) 중고제품테이블, 중고제품사진테이블, 토스페이결제테이블, 중고제품찜하기테이블
-- 채팅방테이블, 채팅메세지테이블 


-- 1️⃣ **제약조건 삭제 (Foreign Key Constraints 먼저 삭제)**
ALTER TABLE USERS DROP CONSTRAINT USERS_ROLE_ID;
ALTER TABLE NORMAL_BOARD DROP CONSTRAINT FK_USER_ID_NORMAL_BOARD;
ALTER TABLE NORMAL_PIC DROP CONSTRAINT FK_NORMAL_BOARD_ID_NORMAL_PIC;
ALTER TABLE NORMAL_COMMENT DROP CONSTRAINT FK_NORMAL_BOARD_ID_NORMAL_COMMENT;
ALTER TABLE NORMAL_COMMENT DROP CONSTRAINT FK_USER_ID_NORMAL_COMMENT;
ALTER TABLE PLACE_BOARD DROP CONSTRAINT FK_USER_ID_PLACE_BOARD;
ALTER TABLE PLACE_PIC DROP CONSTRAINT FK_PLACE_BOARD_ID_PLACE_PIC;
ALTER TABLE PLACE_COMMENT DROP CONSTRAINT FK_PLACE_BOARD_ID_PLACE_COMMENT;
ALTER TABLE PLACE_COMMENT DROP CONSTRAINT FK_USER_ID_PLACE_COMMENT;
ALTER TABLE PLACE_SAVE DROP CONSTRAINT FK_USER_ID_PLACE_SAVE;
ALTER TABLE PLACE_SAVE DROP CONSTRAINT FK_PLACE_BOARD_ID_PLACE_SAVE;
ALTER TABLE PRODUCT DROP CONSTRAINT FK_USER_ID_PRODUCT;
ALTER TABLE PRODUCT_PIC DROP CONSTRAINT FK_PRODUCT_ID_PRODUCT_PIC;
ALTER TABLE PRODUCT_LIKE DROP CONSTRAINT FK_USER_ID_PRODUCT_LIKE;
ALTER TABLE PRODUCT_LIKE DROP CONSTRAINT FK_PRODUCT_ID_PRODUCT;
ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_USER;
ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_SELLER;
ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_PRODUCT;
ALTER TABLE CHAT_ROOM DROP CONSTRAINT FK_SELLER_ID_CHAT_ROOM;
ALTER TABLE CHAT_ROOM DROP CONSTRAINT FK_BUYER_ID_CHAT_ROOM;
ALTER TABLE CHAT_MESSAGE DROP CONSTRAINT FK_CHAT_ROOM_ID_CHAT_MESSAGE;
ALTER TABLE CHAT_MESSAGE DROP CONSTRAINT FK_SENDER_ID_CHAT_MESSAGE;
ALTER TABLE CHAT_PIC DROP CONSTRAINT FK_CHAT_MESSAGE_ID_CHAT_PIC;

-- 2️⃣ **테이블 삭제 (DROP TABLE)**
DROP TABLE ROLE CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS CASCADE CONSTRAINTS PURGE;
DROP TABLE NORMAL_BOARD CASCADE CONSTRAINTS PURGE;
DROP TABLE NORMAL_PIC CASCADE CONSTRAINTS PURGE;
DROP TABLE NORMAL_COMMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE PLACE_BOARD CASCADE CONSTRAINTS PURGE;
DROP TABLE PLACE_PIC CASCADE CONSTRAINTS PURGE;
DROP TABLE PLACE_COMMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE PLACE_SAVE CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT_PIC CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT_LIKE CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDERS CASCADE CONSTRAINTS PURGE;
DROP TABLE CHAT_ROOM CASCADE CONSTRAINTS PURGE;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS PURGE;
DROP TABLE CHAT_PIC CASCADE CONSTRAINTS PURGE;

-- 3️⃣ **시퀀스 삭제 (DROP SEQUENCE)**
DROP SEQUENCE ROLE_SEQ;
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE NORMAL_BOARD_SEQ;
DROP SEQUENCE NORMAL_PIC_SEQ;
DROP SEQUENCE NORMAL_COMMENT_SEQ;
DROP SEQUENCE PLACE_BOARD_SEQ;
DROP SEQUENCE PLACE_PIC_SEQ;
DROP SEQUENCE PLACE_POST_COMMENT_SEQ;
DROP SEQUENCE PLACE_SAVE_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE PRODUCT_PIC_SEQ;
DROP SEQUENCE PRODUCT_LIKE_SEQ;
DROP SEQUENCE CHAT_ROOM_SEQ;
DROP SEQUENCE CHAT_MESSAGE_SEQ;
DROP SEQUENCE CHAT_PIC_SEQ;

COMMIT;



-- 1. 역할 테이블 (ROLE) ------------------------------------------------------------------------------------------
CREATE TABLE ROLE (
    ROLE_ID NUMBER PRIMARY KEY, 
    ROLE_NAME VARCHAR2(50) UNIQUE NOT NULL
);
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (2, 'USER');


-- 2. 유저 테이블 (USERS) ----------------------------------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY, 
    PROVIDER VARCHAR2(30), 
    PROVIDER_ID VARCHAR2(50), 
    USER_EMAIL VARCHAR2(80), 
    PASSWORD VARCHAR2(80), 
    ROLE_ID NUMBER DEFAULT 2, -- FK
    USER_NAME VARCHAR2(80), 
    GENDER VARCHAR2(20), 
    MOBILE1 VARCHAR2(5), 
    MOBILE2 VARCHAR2(8), 
    MOBILE3 VARCHAR2(8), 
    PHONE1 VARCHAR2(5), 
    PHONE2 VARCHAR2(8), 
    PHONE3 VARCHAR2(8), 
    BIRTH VARCHAR2(30), 
    ZIPCODE VARCHAR2(10), 
    ADDRESS1 VARCHAR2(300), 
    ADDRESS2 VARCHAR2(300), 
    USER_REGDATE DATE DEFAULT SYSDATE, 
    ORIGIN_USER VARCHAR2(1000), 
    SYS_USER VARCHAR2(1000)
); 
ALTER TABLE USERS ADD CONSTRAINT USERS_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE CASCADE;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

select * from users;


-- 게시글을 그냥 하나로 통합하고 type으로 나누고 지도 api를 null가능 해서 안보이게 하기
-- NORMAL_BOARD, PLACE_BOARD, PRODUCT -> BOARD (게시글 테이블)
-- NORMAL_COMMENT, PLACE_COMMENT -> BOARD_COMMENT (댓글 테이블)
-- PLACE_SAVE, PRODUCT_LIKE -> BOARD_LIKE (찜하기/추천 테이블)
-- NORMAL_PIC, PLACE_PIC, PRODUCT_PIC -> BOARD_PIC (게시글 사진 테이블)
-- 그러나 게시글만 통합하고 나머지는 냅두라는 지선생의 답변이 잇엇다 
-- 3. 일반 게시글 테이블 (공지사항, QnA, 신고 포함) -------------------------------------------------------------
--CREATE TABLE NORMAL_BOARD (
--    NORMAL_BOARD_ID NUMBER PRIMARY KEY, 
--    NORMAL_BOARD_TYPE VARCHAR2(100) NOT NULL, 
--    NORMAL_BOARD_TITLE VARCHAR2(255) NOT NULL, 
--    NORMAL_BOARD_CONTENT CLOB NOT NULL, 
--    USER_ID NUMBER NOT NULL, -- FK
--    NORMAL_BOARD_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
--    NORMAL_BOARD_VIEWS NUMBER DEFAULT 0
--);
--ALTER TABLE NORMAL_BOARD ADD CONSTRAINT NORMAL_BOARD_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
--CREATE SEQUENCE NORMAL_BOARD_SEQ START WITH 1 INCREMENT BY 1;
--
--
---- 4. 일반 게시글 사진 테이블 ---------------------------------------------------------------------------------
--CREATE TABLE NORMAL_PIC (
--    NORMAL_PIC_ID NUMBER PRIMARY KEY, 
--    NORMAL_BOARD_ID NUMBER NOT NULL, -- FK 
--    NORMAL_PIC_URL VARCHAR2(255) NOT NULL, 
--    NORMAL_PIC_ORDER NUMBER DEFAULT 1
--);
--ALTER TABLE NORMAL_PIC ADD CONSTRAINT NORMAL_PIC_NORMAL_BOARD_ID FOREIGN KEY (NORMAL_BOARD_ID) REFERENCES NORMAL_BOARD(NORMAL_BOARD_ID) ON DELETE CASCADE;
--CREATE SEQUENCE NORMAL_PIC_SEQ START WITH 1 INCREMENT BY 1;
--
--
---- 5. 일반 게시글 댓글 테이블 ---------------------------------------------------------------------------------
--CREATE TABLE NORMAL_COMMENT (
--    NORMAL_COMMENT_ID NUMBER PRIMARY KEY, 
--    NORMAL_BOARD_ID NUMBER NOT NULL, -- FK
--    USER_ID NUMBER NOT NULL, -- FK
--    NORMAL_COMMENT_CONTENT CLOB NOT NULL, 
--    NORMAL_COMMENT_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--ALTER TABLE NORMAL_COMMENT ADD CONSTRAINT NORMAL_COMMENT_NORMAL_BOARD_ID FOREIGN KEY (NORMAL_BOARD_ID) REFERENCES NORMAL_BOARD(NORMAL_BOARD_ID) ON DELETE CASCADE;
--ALTER TABLE NORMAL_COMMENT ADD CONSTRAINT NORMAL_COMMENT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
--CREATE SEQUENCE NORMAL_COMMENT_SEQ START WITH 1 INCREMENT BY 1;


-- 6. 장소 게시글 테이블 -------------------------------------------------------------------------------------
CREATE TABLE PLACE_BOARD (
    PLACE_BOARD_ID NUMBER PRIMARY KEY, 
    PLACE_BOARD_TITLE VARCHAR2(300), 
    PLACE_BOARD_CONTENT CLOB, 
    USER_ID NUMBER, -- FK
    PLACE_BOARD_ADDRESS VARCHAR2(300), 
    PLACE_BOARD_LAT NUMBER(10, 6), 
    PLACE_BOARD_LNG NUMBER(10, 6), 
    PLACE_BOARD_PLACE_ID VARCHAR2(300),  -- API
    PLACE_BOARD_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PLACE_BOARD_VIEWS NUMBER DEFAULT 0
);
ALTER TABLE PLACE_BOARD ADD CONSTRAINT PLACE_BOARD_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE PLACE_BOARD_SEQ START WITH 1 INCREMENT BY 1;


-- 7. 장소 게시글 사진 테이블 ---------------------------------------------------------------------------------
CREATE TABLE PLACE_PIC (
    PLACE_PIC_ID NUMBER PRIMARY KEY, 
    PLACE_BOARD_ID NUMBER NOT NULL, -- FK
    PLACE_PIC_URL VARCHAR2(500), 
    PLACE_PIC_ORDER NUMBER DEFAULT 1
);
ALTER TABLE PLACE_PIC ADD CONSTRAINT PLACE_PIC_PLACE_BOARD_ID FOREIGN KEY (PLACE_BOARD_ID) REFERENCES PLACE_BOARD(PLACE_BOARD_ID) ON DELETE CASCADE;
CREATE SEQUENCE PLACE_PIC_SEQ START WITH 1 INCREMENT BY 1;


-- 8. 장소 게시글 댓글 테이블 ---------------------------------------------------------------------------------
CREATE TABLE PLACE_COMMENT (
    PLACE_COMMENT_ID NUMBER PRIMARY KEY, 
    PLACE_BOARD_ID NUMBER NOT NULL, -- FK 
    USER_ID NUMBER NOT NULL, -- FK
    PLACE_COMMENT_CONTENT CLOB, 
    PLACE_COMMENT_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE PLACE_COMMENT ADD CONSTRAINT PLACE_COMMENT_PLACE_BOARD_ID FOREIGN KEY (PLACE_BOARD_ID) REFERENCES PLACE_BOARD(PLACE_BOARD_ID) ON DELETE CASCADE;
ALTER TABLE PLACE_COMMENT ADD CONSTRAINT PLACE_COMMENT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE PLACE_POST_COMMENT_SEQ START WITH 1 INCREMENT BY 1;

-- 9. 장소 게시글 저장 테이블
CREATE TABLE PLACE_SAVE (
    PLACE_SAVE_ID NUMBER PRIMARY KEY, 
    USER_ID NUMBER NOT NULL, -- FK
    PLACE_BOARD_ID NUMBER NOT NULL, -- FK
    SAVE_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
ALTER TABLE PLACE_SAVE ADD CONSTRAINT PLACE_SAVE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE PLACE_SAVE ADD CONSTRAINT PLACE_SAVE_PLACE_BOARD_ID FOREIGN KEY (PLACE_BOARD_ID) REFERENCES PLACE_BOARD(PLACE_BOARD_ID) ON DELETE CASCADE;
ALTER TABLE PLACE_SAVE ADD CONSTRAINT UQ_PLACE_SAVE UNIQUE (USER_ID, PLACE_BOARD_ID);
CREATE SEQUENCE PLACE_SAVE_SEQ START WITH 1 INCREMENT BY 1;


-- 10. 중고 제품 테이블 ----------------------------------------------------------------------------------------
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY, 
    PRODUCT_NAME VARCHAR2(255) NOT NULL, 
    PRODUCT_PRICE NUMBER(10, 2) NOT NULL, 
    PRODUCT_TYPE VARCHAR2(100) NOT NULL, 
    PRODUCT_DETAIL CLOB NOT NULL, 
    USER_ID NUMBER NOT NULL, -- FK
    PRODUCT_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRODUCT_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;


-- 11. 중고 제품 사진 테이블 ---------------------------------------------------------------------------------
CREATE TABLE PRODUCT_PIC (
    PRODUCT_PIC_ID NUMBER PRIMARY KEY, 
    PRODUCT_ID NUMBER NOT NULL, -- FK
    PRODUCT_PIC_URL VARCHAR2(255) NOT NULL, 
    PRODUCT_PIC_ORDER NUMBER DEFAULT 1
);
ALTER TABLE PRODUCT_PIC ADD CONSTRAINT PRODUCT_PIC_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE;
CREATE SEQUENCE PRODUCT_PIC_SEQ START WITH 1 INCREMENT BY 1;


-- 12. 중고 제품 찜하기 테이블 -----------------------------------------------------------------------------
CREATE TABLE PRODUCT_LIKE (
    PRODUCT_LIKE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL, -- FK
    PRODUCT_ID NUMBER NOT NULL, -- FK
    PRODUCT_LIKE_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE PRODUCT_LIKE ADD CONSTRAINT PRODUCT_LIKE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE PRODUCT_LIKE ADD CONSTRAINT PRODUCT_LIKE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE;
CREATE SEQUENCE PRODUCT_LIKE_SEQ START WITH 1 INCREMENT BY 1;

-- 시퀀스 없음
-- 13. 토스페이 결제 테이블 (ORDERS) 
CREATE TABLE ORDERS (
    ORDER_ID VARCHAR2(50) PRIMARY KEY,                -- 주문번호 (토스페이 제공)
    USER_ID NUMBER NOT NULL,                          -- 구매자 ID (FK)
    SELLER_ID NUMBER NOT NULL,                        -- 판매자 ID (FK)
    PRODUCT_ID NUMBER NOT NULL,                       -- 상품 ID (FK)
    TOTAL_AMOUNT NUMBER(19,2) NOT NULL,               -- 결제 금액
    PAYMENT_METHOD VARCHAR2(20) DEFAULT '카드' NOT NULL, -- 결제 수단 (카드, 계좌이체 등)
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,   -- 결제 상태 (PENDING, SUCCESS, CANCELED)
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,   -- 결제일자
    PAYMENT_KEY VARCHAR2(100) UNIQUE NOT NULL,        -- 토스페이 결제 키
    CUSTOMER_NAME VARCHAR2(50) NOT NULL,              -- 구매자 이름 (실명 인증 필요할 수도 있음)
    SELLER_NAME VARCHAR2(50) NOT NULL,                -- 판매자 이름
    CANCEL_DATE TIMESTAMP                             -- 결제 취소 일자 (NULL 가능)
);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_SELLER_ID FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE;



-- 애초에 채팅방 유지할지 고민중
-- 14. 채팅방 테이블 -------------------------------------------------------------------------------------
--CREATE TABLE CHAT_ROOM (
--    CHAT_ROOM_ID NUMBER PRIMARY KEY, 
--    SELLER_ID NUMBER NOT NULL, -- FK
--    BUYER_ID NUMBER NOT NULL, -- FK
--    CHAT_ROOM_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--ALTER TABLE CHAT_ROOM ADD CONSTRAINT CHAT_ROOM_SELLER_ID FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
--ALTER TABLE CHAT_ROOM ADD CONSTRAINT CHAT_ROOM_BUYER_ID FOREIGN KEY (BUYER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
--CREATE SEQUENCE CHAT_ROOM_SEQ START WITH 1 INCREMENT BY 1;
--
--
---- 15. 채팅 메시지 테이블 -----------------------------------------------------------------------------------
--CREATE TABLE CHAT_MESSAGE (
--    CHAT_MESSAGE_ID NUMBER PRIMARY KEY, 
--    CHAT_ROOM_ID NUMBER NOT NULL, -- FK
--    SENDER_ID NUMBER NOT NULL, -- FK
--    CHAT_MESSAGE_CONTENT CLOB NOT NULL, 
--    CHAT_MESSAGE_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT CHAT_MESSAGE_CHAT_ROOM_ID FOREIGN KEY (CHAT_ROOM_ID) REFERENCES CHAT_ROOM(CHAT_ROOM_ID) ON DELETE CASCADE;
--ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT CHAT_MESSAGE_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
--CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;
--
--
---- 16. 채팅 메시지 파일 테이블 (빼는게 나을듯 너무 테이블이 많음) -----------------------------------------------------------------------------------
--CREATE TABLE CHAT_PIC (
--    CHAT_PIC_ID NUMBER PRIMARY KEY,                   
--    CHAT_MESSAGE_ID NUMBER NOT NULL, -- FK                   
--    CHAT_PIC_URL VARCHAR2(500) NOT NULL,              
--    CHAT_PIC_ORDER NUMBER DEFAULT 1 NOT NULL          
--);
--ALTER TABLE CHAT_PIC ADD CONSTRAINT CHAT_PIC_CHAT_MESSAGE_ID FOREIGN KEY (CHAT_MESSAGE_ID) REFERENCES CHAT_MESSAGE(CHAT_MESSAGE_ID) ON DELETE CASCADE;
--CREATE SEQUENCE CHAT_PIC_SEQ START WITH 1 INCREMENT BY 1;


