---- 제약조건 삭제 (Foreign Key Constraints)
--ALTER TABLE USERS DROP CONSTRAINT USERS_ROLE_ID;
--ALTER TABLE BOARD DROP CONSTRAINT BOARD_USER_ID;
--ALTER TABLE BOARD_PIC DROP CONSTRAINT BOARD_PIC_BOARD_ID;
--ALTER TABLE BOARD_COMMENT DROP CONSTRAINT BOARD_COMMENT_BOARD_ID;
--ALTER TABLE BOARD_COMMENT DROP CONSTRAINT BOARD_COMMENT_USER_ID;
--ALTER TABLE BOARD_SAVE DROP CONSTRAINT BOARD_SAVE_USER_ID;
--ALTER TABLE BOARD_SAVE DROP CONSTRAINT BOARD_SAVE_BOARD_ID;
--ALTER TABLE PRODUCT DROP CONSTRAINT PRODUCT_USER_ID;
--ALTER TABLE PRODUCT_PIC DROP CONSTRAINT PRODUCT_PIC_PRODUCT_ID;
--ALTER TABLE PRODUCT_LIKE DROP CONSTRAINT PRODUCT_LIKE_USER_ID;
--ALTER TABLE PRODUCT_LIKE DROP CONSTRAINT PRODUCT_LIKE_PRODUCT_ID;
--ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_USER_ID;
--ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_PRODUCT_ID;
--ALTER TABLE CHAT_ROOM DROP CONSTRAINT FK_SELLER_ID_CHAT_ROOM;
--ALTER TABLE CHAT_ROOM DROP CONSTRAINT FK_BUYER_ID_CHAT_ROOM;
--ALTER TABLE CHAT_MESSAGE DROP CONSTRAINT FK_CHAT_ROOM_ID_CHAT_MESSAGE;
--ALTER TABLE CHAT_MESSAGE DROP CONSTRAINT FK_SENDER_ID_CHAT_MESSAGE;
--ALTER TABLE CHAT_PIC DROP CONSTRAINT FK_CHAT_MESSAGE_ID_CHAT_PIC;
--
--
---- 테이블 삭제 (Tables)
--DROP TABLE CHAT_PIC;
--DROP TABLE CHAT_MESSAGE;
--DROP TABLE CHAT_ROOM;
--DROP TABLE ORDERS;
--DROP TABLE PRODUCT_LIKE;
--DROP TABLE PRODUCT_PIC;
--DROP TABLE PRODUCT;
--DROP TABLE BOARD_SAVE;
--DROP TABLE BOARD_COMMENT;
--DROP TABLE BOARD_PIC;
--DROP TABLE BOARD;
--DROP TABLE USERS;
--DROP TABLE ROLE;
--
--
---- 시퀀스 삭제 (Sequences)
--DROP SEQUENCE CHAT_PIC_SEQ;
--DROP SEQUENCE CHAT_MESSAGE_SEQ;
--DROP SEQUENCE CHAT_ROOM_SEQ;
--DROP SEQUENCE PRODUCT_LIKE_SEQ;
--DROP SEQUENCE PRODUCT_PIC_SEQ;
--DROP SEQUENCE PRODUCT_SEQ;
--DROP SEQUENCE BOARD_SAVE_SEQ;
--DROP SEQUENCE BOARD_COMMENT_SEQ;
--DROP SEQUENCE BOARD_PIC_SEQ;
--DROP SEQUENCE BOARD_SEQ;
--DROP SEQUENCE USERS_SEQ;
--DROP SEQUENCE ROLE_SEQ;
--
---- 4. COMMIT으로 반영
--COMMIT;


-- 1. 역할 테이블 (ROLE)
CREATE TABLE ROLE (
    ROLE_ID NUMBER PRIMARY KEY, 
    ROLE_NAME VARCHAR2(50)
);
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (2, 'USER');

-- 2. 유저 테이블 (USERS)
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY, 
    PROVIDER VARCHAR2(30), 
    PROVIDER_ID VARCHAR2(50), 
    USER_EMAIL VARCHAR2(80),
    PASSWORD VARCHAR2(300), 
    ROLE_ID NUMBER NOT NULL, 
    USER_NAME VARCHAR2(80), 
    GENDER VARCHAR2(20), 
    MOBILE VARCHAR2(15),
    PHONE VARCHAR2(15),
    BIRTH VARCHAR2(30), 
    ZIPCODE VARCHAR2(10), 
    ADDRESS1 VARCHAR2(300), 
    ADDRESS2 VARCHAR2(300), 
    USER_REGDATE DATE DEFAULT SYSDATE, 
    ORIGIN_USER VARCHAR2(1000), 
    SYS_USER VARCHAR2(1000)
); 
ALTER TABLE USERS ADD CONSTRAINT USERS_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE CASCADE;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE USERS ADD CONSTRAINT UNIQUE_PROVIDER_ID UNIQUE (PROVIDER, PROVIDER_ID);
ALTER TABLE USERS DROP CONSTRAINT UNIQUE_PROVIDER_ID;
commit;



select * from users;
select * from users where user_id = 1;
commit;

SELECT * FROM USERS ORDER BY USER_ID DESC;
commit;
-- 3. 게시글 테이블 (BOARD)`
CREATE TABLE BOARD (
    BOARD_ID NUMBER PRIMARY KEY, 
    BOARD_TYPE VARCHAR2(30),
    BOARD_TITLE VARCHAR2(300), 
    BOARD_CONTENT CLOB, 
    USER_ID NUMBER NOT NULL, 
    BOARD_ADDRESS VARCHAR2(300), 
    BOARD_LAT NUMBER(10, 6), 
    BOARD_LNG NUMBER(10, 6), 
    PLACE_ID VARCHAR2(300),  
    BOARD_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    BOARD_VIEWS NUMBER DEFAULT 0
);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;  
select * from board;

-- 사용자 1명이 있다고 가정 (user_id = 1)
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '자유게시판', '첫 번째 게시글입니다',
    '게시글 내용이 여기에 들어갑니다.', 1,
    '서울특별시 강남구 테헤란로 123', 37.5010, 127.0396, 'place_123'
);

INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '정보게시판', '두 번째 게시글입니다',
    '이 게시글은 정보를 공유합니다.', 1,
    '부산광역시 해운대구 센텀중앙로 456', 35.1801, 129.1197, 'place_456'
);

-- 공지사항
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '공지사항', '공지사항 테스트 게시글',
    '이것은 공지사항입니다.', 1,
    '서울시 종로구', 37.5729, 126.9794, 'notice_001'
);


-- 자유게시판
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '자유게시판', '자유게시판 테스트 게시글',
    '자유롭게 글을 써보세요!', 1,
    '서울시 마포구', 37.5563, 126.9220, 'free_001'
);

-- 취미게시판
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '취미게시판', '취미 공유해요!',
    '여러분의 취미를 공유해보세요.', 1,
    '서울시 성동구', 37.5610, 127.0364, 'hobby_001'
);

-- 놀거리게시판
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '놀거리게시판', '주말에 뭐할까?',
    '재밌는 놀거리 추천해요!', 1,
    '서울시 용산구', 37.5311, 126.9784, 'play_001'
);

-- 맛집게시판
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '맛집게시판', '이 동네 맛집 추천!',
    '진짜 맛있는 집 공유해요.', 1,
    '서울시 강동구', 37.5286, 127.1247, 'food_001'
);

-- 거래게시판
INSERT INTO board (
    board_id, board_type, board_title, board_content, user_id,
    board_address, board_lat, board_lng, place_id
) VALUES (
    BOARD_SEQ.NEXTVAL, '거래게시판', '노트북 팝니다',
    '중고 노트북 좋은 가격에 드려요.', 1,
    '서울시 관악구', 37.4784, 126.9516, 'sell_001'
);

COMMIT;

UPDATE board SET board_type = 'notice'     WHERE board_type = '공지사항';
UPDATE board SET board_type = 'free'       WHERE board_type = '자유게시판';
UPDATE board SET board_type = 'hobby'      WHERE board_type = '취미게시판';
UPDATE board SET board_type = 'play'       WHERE board_type = '놀거리게시판';
UPDATE board SET board_type = 'food'       WHERE board_type = '맛집게시판';
UPDATE board SET board_type = 'sell'       WHERE board_type = '거래게시판';
COMMIT;

select * from board;



-- 4. 게시글 사진 테이블 (BOARD_PIC)
CREATE TABLE BOARD_PIC (
    BOARD_PIC_ID NUMBER PRIMARY KEY, 
    BOARD_ID NUMBER NOT NULL, 
    BOARD_PIC_URL VARCHAR2(500), 
    BOARD_PIC_ORDER NUMBER DEFAULT 1
);
ALTER TABLE BOARD_PIC ADD CONSTRAINT BOARD_PIC_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE;
CREATE SEQUENCE BOARD_PIC_SEQ START WITH 1 INCREMENT BY 1;


-- 첫 번째 게시글에 이미지 2장
INSERT INTO board_pic (
    board_pic_id, board_id, board_pic_url, board_pic_order
) VALUES (
    BOARD_PIC_SEQ.NEXTVAL, 1, 'https://example.com/images/post1_img1.jpg', 1
);

INSERT INTO board_pic (
    board_pic_id, board_id, board_pic_url, board_pic_order
) VALUES (
    BOARD_PIC_SEQ.NEXTVAL, 1, 'https://example.com/images/post1_img2.jpg', 2
);

-- 두 번째 게시글에 이미지 1장
INSERT INTO board_pic (
    board_pic_id, board_id, board_pic_url, board_pic_order
) VALUES (
    BOARD_PIC_SEQ.NEXTVAL, 2, 'https://example.com/images/post2_img1.jpg', 1
);

commit;
-- 5. 게시글 댓글 테이블 (BOARD_COMMENT)
CREATE TABLE BOARD_COMMENT (
    BOARD_COMMENT_ID NUMBER PRIMARY KEY, 
    BOARD_ID NUMBER NOT NULL, 
    USER_ID NUMBER NOT NULL, 
    BOARD_COMMENT_CONTENT CLOB, 
    BOARD_COMMENT_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT BOARD_COMMENT_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE;
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT BOARD_COMMENT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE BOARD_COMMENT_SEQ START WITH 1 INCREMENT BY 1;

-- 6. 게시글 저장 테이블 (BOARD_SAVE)
CREATE TABLE BOARD_SAVE (
    BOARD_SAVE_ID NUMBER PRIMARY KEY, 
    USER_ID NUMBER NOT NULL, 
    BOARD_ID NUMBER NOT NULL, 
    BOARD_SAVE_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
ALTER TABLE BOARD_SAVE ADD CONSTRAINT BOARD_SAVE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE BOARD_SAVE ADD CONSTRAINT BOARD_SAVE_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE;
CREATE SEQUENCE BOARD_SAVE_SEQ START WITH 1 INCREMENT BY 1;

-- UNIQUE INDEX를 먼저 생성 후 UNIQUE CONSTRAINT 추가
--CREATE UNIQUE INDEX BOARD_SAVE_IDX ON BOARD_SAVE(USER_ID, BOARD_ID);
--ALTER TABLE BOARD_SAVE ADD CONSTRAINT BOARD_SAVE UNIQUE (USER_ID, BOARD_ID) USING INDEX BOARD_SAVE_IDX;
--ALTER TABLE BOARD_SAVE ADD CONSTRAINT BOARD_SAVE UNIQUE (USER_ID, BOARD_ID);

-- 7. 제품 테이블 (PRODUCT)
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY, 
    PRODUCT_NAME VARCHAR2(255), 
    PRODUCT_PRICE NUMBER(12), 
    PRODUCT_NUM NUMBER(10),
    PRODUCT_TYPE VARCHAR2(100), 
    PRODUCT_DETAIL CLOB, 
    USER_ID NUMBER NOT NULL, 
    PRODUCT_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRODUCT_STATUS VARCHAR2(20) DEFAULT '판매중',
    PRODUCT_ADDRESS VARCHAR2(255),  
    PRODUCT_LAT NUMBER(10, 6),  
    PRODUCT_LNG NUMBER(10, 6),  
    PRODUCT_PLACE_ID VARCHAR2(100)  
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;

-- 8. 제품 사진 테이블 (PRODUCT_PIC)
CREATE TABLE PRODUCT_PIC (
    PRODUCT_PIC_ID NUMBER PRIMARY KEY, 
    PRODUCT_ID NUMBER NOT NULL, 
    PRODUCT_PIC_URL VARCHAR2(255), 
    PRODUCT_PIC_ORDER NUMBER DEFAULT 1
);
ALTER TABLE PRODUCT_PIC ADD CONSTRAINT PRODUCT_PIC_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE;
CREATE SEQUENCE PRODUCT_PIC_SEQ START WITH 1 INCREMENT BY 1;

-- 9. 제품 찜하기 테이블 (PRODUCT_LIKE)
CREATE TABLE PRODUCT_LIKE (
    PRODUCT_LIKE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL, 
    PRODUCT_ID NUMBER NOT NULL, 
    PRODUCT_LIKE_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE PRODUCT_LIKE ADD CONSTRAINT PRODUCT_LIKE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE PRODUCT_LIKE ADD CONSTRAINT PRODUCT_LIKE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE;
CREATE SEQUENCE PRODUCT_LIKE_SEQ START WITH 1 INCREMENT BY 1;

-- 10. 결제 테이블 (ORDERS)
CREATE TABLE ORDERS (
    ORDER_ID VARCHAR2(50) PRIMARY KEY,  
    USER_ID NUMBER NOT NULL, 
    PRODUCT_ID NUMBER NOT NULL, 
    PRODUCT_NAME VARCHAR2(255) NOT NULL,  
    PAYMENT_METHOD VARCHAR2(20) DEFAULT '카드' NOT NULL,  
    TOTAL_AMOUNT NUMBER(19,0) NOT NULL,  
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,  
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    PAYMENT_KEY VARCHAR2(100) UNIQUE,  
    CUSTOMER_NAME VARCHAR2(50),  
    SELLER_NAME VARCHAR2(50)  
);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE;

commit;







-------------------------------------------------------------------------------------------------------------------------------------

-- 12. 채팅방 테이블 -------------------------------------------------------------------------------------
CREATE TABLE CHAT_ROOM (
    CHAT_ROOM_ID NUMBER PRIMARY KEY, 
    SELLER_ID NUMBER NOT NULL, -- FK
    BUYER_ID NUMBER NOT NULL, -- FK
    CHAT_ROOM_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE CHAT_ROOM ADD CONSTRAINT FK_SELLER_ID_CHAT_ROOM FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE CHAT_ROOM ADD CONSTRAINT FK_BUYER_ID_CHAT_ROOM FOREIGN KEY (BUYER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE CHAT_ROOM_SEQ START WITH 1 INCREMENT BY 1;


-- 13. 채팅 메시지 테이블 -----------------------------------------------------------------------------------
CREATE TABLE CHAT_MESSAGE (
    CHAT_MESSAGE_ID NUMBER PRIMARY KEY, 
    CHAT_ROOM_ID NUMBER NOT NULL, -- FK
    SENDER_ID NUMBER NOT NULL, -- FK
    CHAT_MESSAGE_CONTENT CLOB NOT NULL, 
    CHAT_MESSAGE_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_ROOM_ID_CHAT_MESSAGE FOREIGN KEY (CHAT_ROOM_ID) REFERENCES CHAT_ROOM(CHAT_ROOM_ID) ON DELETE CASCADE;
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_SENDER_ID_CHAT_MESSAGE FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;


-- 14. 채팅 메시지 파일 테이블 -----------------------------------------------------------------------------------
CREATE TABLE CHAT_PIC (
    CHAT_PIC_ID NUMBER PRIMARY KEY,                   
    CHAT_MESSAGE_ID NUMBER NOT NULL, -- FK                   
    CHAT_PIC_URL VARCHAR2(500) NOT NULL,              
    CHAT_PIC_ORDER NUMBER DEFAULT 1 NOT NULL          
);
ALTER TABLE CHAT_PIC ADD CONSTRAINT FK_CHAT_MESSAGE_ID_CHAT_PIC FOREIGN KEY (CHAT_MESSAGE_ID) REFERENCES CHAT_MESSAGE(CHAT_MESSAGE_ID) ON DELETE CASCADE;    
CREATE SEQUENCE CHAT_PIC_SEQ START WITH 1 INCREMENT BY 1;




